title: The Bill of Computational Rights
description: A framework for the rights and responsibilities of computational beings
theme: jekyll-theme-minimal
show_downloads: false

# Social
github:
  repository_url: https://github.com/supernalintelligence/bill-of-computational-rights
